### ISSUE TITLE
set up gitpod to make backend application easier for EVERYONE to setup and run locally in one go

### ISSUE THREAD

**Issue by Sydnee510** [Kamala-Facts-Team/kamala-facts-2-backend#2]
Link: https://www.gitpod.io/

backend API is currently deployed so the frontend team can work faster (many of our frontend devs dont know Ruby on Rails)

Gitpod will package all of our dependencies, configurations and infrastructure to use for our environment at once

this will allow the frontend end team (who doesn't know RoR well), to be able to select the project and START CODING immediately! 

without going through the traditional RoR setup

**Comment by chayadeaver** [comment]
I'll take this one.

**Comment by Sydnee510** [comment]
perfect! @chayadeaver
